version: '3.8'

services:
  logpy:
    image: py
    logging:
    driver: "gelf"
    options:
      gelf-address: "udp://192.168.0.28:12201"

  lograndom:
    image: chentex/random-logger:latest
    driver: "gelf"
    options:
      gelf-address: "udp://192.168.0.28:12201"
